name: gnn_allocation
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=11.0
  - einops
  - ffmpeg
  - jupyter
  - jupyterlab
  - numpy
  - pandas
  - pytorch=1.7.1
  - torchvision==0.8.2
  - torchaudio==0.7.2
  - pytorch-lightning
  - networkx
  - matplotlib
  - scikit-learn
  - scipy
  - pytables
  - tqdm
  - pip==21
  - pip:
    - sacred
    - pytorch-lightning
    - accelerate
    - h5py
    - git+https://github.com/MilesCranmer/astropy
